names = ['Alex', 'Jordan', 'Taylor',]
print(names[0] + " is invited to the party!")
print(names[1] + " is invited to the party!")   
print(names[2] + " is invited to the party!")  
print("Unfortunately, " + names[1] + " can't make it to the party.")
names[1] = 'Morgan'
print(names[0] + " is invited to the party!")
print(names[1] + " is invited to the party!")   
print(names[2] + " is invited to the party!") 
print("Good news! We found a bigger table, so more guests can come to the party!")
names.insert(0, 'Charlie')
names.insert(2, 'Sam')
names.append('Max')
print(names[0] + " is invited to the party!")
print(names[1] + " is invited to the party!")
print(names[2] + " is invited to the party!")
print(names[3] + " is invited to the party!")
print(names[4] + " is invited to the party!")
print(names[5] + " is invited to the party!")